DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar (250) unique NOT NULL,
    password varchar (250),
    birthday DATE
);

DROP TABLE IF EXISTS accounts CASCADE;
CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance FLOAT,
    CONSTRAINT fk_account_id FOREIGN KEY (account_id) REFERENCES users (user_id)
);

DROP TABLE IF EXISTS phones CASCADE;
CREATE TABLE IF NOT EXISTS phones (
    user_id BIGINT REFERENCES users(user_id),
    phone varchar(25) unique NOT NULL
);

DROP TABLE IF EXISTS emails CASCADE;
CREATE TABLE IF NOT EXISTS emails (
    user_id BIGINT REFERENCES users(user_id),
    email varchar(50) unique NOT NULL
);

